name: Setup
description: Setup
runs:
  using: "composite"
  steps:
    - name: Install
      run: |
        apk update \
          && apk add git \
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.8
      shell: sh